package server

import (
	_ "log/syslog"
	"start/common/controllers"
	"start/middlewares"

	// _ "start/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gin-gonic/gin"
	// ginSwagger "github.com/swaggo/gin-swagger"
	// "github.com/swaggo/gin-swagger/swaggerFiles"
)

func NewRouter() *gin.Engine {
	router := gin.New()
	router.GET("/", func(c *gin.Context) {
		c.JSON(200, gin.H{"message": "Hello my template"})
		c.Abort()
		return
	})
	// ==========customer api
	customerApi := router.Group("customers").Use(middlewares.VerifyJwtToken())
	{
		cCustomer := new(controllers.CustomerController)
		customerApi.GET("/", cCustomer.CheckRequest)
		customerApi.POST("/refresh", cCustomer.CheckRequest)
		customerApi.POST("/upload-file", cCustomer.Upload)
	}

	return router
}
